# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 375c66208b9bd147beede794ce1014a9c41a6f9a69c557ccfe21be17719eed58bc952df0bec008b2efef0f0f6b412bf23b5b55e08da5f4dab859bcd0c344e8af

test:
  secret_key_base: 3cf3a0ff02f244223beb0f8c457d57706750526fd30e068cf2b89864e36b78bea5b619fc34580f015f3b8eb74947ecf0679b67f805ca8efaf43f89cd1f897f84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
